/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { ArrayProductionDirectiveTaskUpdateWithIdDto } from './ArrayProductionDirectiveTaskUpdateWithIdDto';
import type { DirectiveCreateDto } from './DirectiveCreateDto';
import type { DirectiveUpdateWithIdDto } from './DirectiveUpdateWithIdDto';
import type { EntityLinkUpsertsDto } from './EntityLinkUpsertsDto';
import type { InventoryItemGroupCreateDto } from './InventoryItemGroupCreateDto';
import type { InventoryItemGroupUpdateWithIdDto } from './InventoryItemGroupUpdateWithIdDto';
import type { NonProductionDirectiveCreateDto } from './NonProductionDirectiveCreateDto';
import type { NonProductionDirectiveUpdateWithIdDto } from './NonProductionDirectiveUpdateWithIdDto';
import type { OrderAcknowledgementCreateDto } from './OrderAcknowledgementCreateDto';
import type { OrderAcknowledgementUpdateWithIdDto } from './OrderAcknowledgementUpdateWithIdDto';
import type { ProductionDirectiveCreateDto } from './ProductionDirectiveCreateDto';
import type { ProductionDirectiveUpdateWithIdDto } from './ProductionDirectiveUpdateWithIdDto';
import type { ProjectCreateDto } from './ProjectCreateDto';
import type { ProjectExtraCreateDto } from './ProjectExtraCreateDto';
import type { ProjectExtraUpdateWithIdDto } from './ProjectExtraUpdateWithIdDto';
import type { ProjectPhaseCreateDto } from './ProjectPhaseCreateDto';
import type { ProjectPhaseUpdateWithIdDto } from './ProjectPhaseUpdateWithIdDto';
import type { ProjectShippingLocationCreateDto } from './ProjectShippingLocationCreateDto';
import type { ProjectShippingLocationUpdateWithIdDto } from './ProjectShippingLocationUpdateWithIdDto';
import type { ProjectStatusUpdateCreateDto } from './ProjectStatusUpdateCreateDto';
import type { ProjectStatusUpdateUpdateWithIdDto } from './ProjectStatusUpdateUpdateWithIdDto';
import type { ProjectSystemComponentCreateDto } from './ProjectSystemComponentCreateDto';
import type { ProjectSystemComponentUpdateWithIdDto } from './ProjectSystemComponentUpdateWithIdDto';
import type { ProjectSystemCreateDto } from './ProjectSystemCreateDto';
import type { ProjectSystemUpdateWithIdDto } from './ProjectSystemUpdateWithIdDto';
import type { ProjectUpdateWithIdDto } from './ProjectUpdateWithIdDto';
import type { PurchaseRequestCreateDto } from './PurchaseRequestCreateDto';
import type { PurchaseRequestRequestedUpsertItemsDto } from './PurchaseRequestRequestedUpsertItemsDto';
import type { PurchaseRequestUpdateWithIdDto } from './PurchaseRequestUpdateWithIdDto';
import type { RFICreateDto } from './RFICreateDto';
import type { RFIUpdateWithIdDto } from './RFIUpdateWithIdDto';
import type { ServiceTaskCreateDto } from './ServiceTaskCreateDto';
import type { ServiceTaskProductionDirectiveUpsertDto } from './ServiceTaskProductionDirectiveUpsertDto';
import type { ServiceTaskUpdateWithIdDto } from './ServiceTaskUpdateWithIdDto';
import type { SubmittalCreateDto } from './SubmittalCreateDto';
import type { SubmittalUpdateWithIdDto } from './SubmittalUpdateWithIdDto';
import type { TransmittalCreateDto } from './TransmittalCreateDto';
import type { TransmittalUpdateWithIdDto } from './TransmittalUpdateWithIdDto';
import type { UpdateSubmittalsDto } from './UpdateSubmittalsDto';
import type { UpsertOrderAcknowledgementDrawingSubmittalsDto } from './UpsertOrderAcknowledgementDrawingSubmittalsDto';
import type { UpsertOrderAcknowledgementMaterialAquisitionLeadTimesDto } from './UpsertOrderAcknowledgementMaterialAquisitionLeadTimesDto';
import type { UpsertOrderAcknowledgementMaterialFabricationAndDeliveriesDto } from './UpsertOrderAcknowledgementMaterialFabricationAndDeliveriesDto';
import type { UpsertProjectDocumentFilesDto } from './UpsertProjectDocumentFilesDto';
import type { UpsertProjectStatusUpdateDrawingSubmittalsDto } from './UpsertProjectStatusUpdateDrawingSubmittalsDto';
import type { UpsertProjectStatusUpdateMaterialAquisitionLeadTimesDto } from './UpsertProjectStatusUpdateMaterialAquisitionLeadTimesDto';
import type { UpsertProjectStatusUpdateMaterialFabricationAndDeliveriesDto } from './UpsertProjectStatusUpdateMaterialFabricationAndDeliveriesDto';
import type { UpsertSubmittalsDto } from './UpsertSubmittalsDto';

export type ProjectWithDataUpdateDto = {
  createProject?: ProjectCreateDto;
  updateProject?: ProjectUpdateWithIdDto;
  createShippingLocations?: Array<ProjectShippingLocationCreateDto> | null;
  updateShippingLocations?: Array<ProjectShippingLocationUpdateWithIdDto> | null;
  createExtra?: ProjectExtraCreateDto;
  updateExtra?: ProjectExtraUpdateWithIdDto;
  createPhase?: ProjectPhaseCreateDto;
  updatePhase?: ProjectPhaseUpdateWithIdDto;
  createDirective?: DirectiveCreateDto;
  updateDirective?: DirectiveUpdateWithIdDto;
  createProductionDirective?: ProductionDirectiveCreateDto;
  updateProductionDirective?: ProductionDirectiveUpdateWithIdDto;
  updateProductionDirectiveTasks?: ArrayProductionDirectiveTaskUpdateWithIdDto;
  createNonProductionDirective?: NonProductionDirectiveCreateDto;
  updateNonProductionDirective?: NonProductionDirectiveUpdateWithIdDto;
  createInventoryItemGroup?: InventoryItemGroupCreateDto;
  updateInventoryItemGroup?: InventoryItemGroupUpdateWithIdDto;
  createProjectSystem?: ProjectSystemCreateDto;
  updateProjectSystem?: ProjectSystemUpdateWithIdDto;
  createProjectSystemComponent?: ProjectSystemComponentCreateDto;
  updateProjectSystemComponent?: ProjectSystemComponentUpdateWithIdDto;
  createPurchaseRequest?: PurchaseRequestCreateDto;
  updatePurchaseRequest?: PurchaseRequestUpdateWithIdDto;
  upsertPurchaseRequestItems?: PurchaseRequestRequestedUpsertItemsDto;
  createProjectStatusUpdate?: ProjectStatusUpdateCreateDto;
  updateProjectStatusUpdate?: ProjectStatusUpdateUpdateWithIdDto;
  upsertProjectStatusUpdateDrawingSubmittals?: UpsertProjectStatusUpdateDrawingSubmittalsDto;
  upsertProjectStatusUpdateMaterialAquisitionLeadTimes?: UpsertProjectStatusUpdateMaterialAquisitionLeadTimesDto;
  upsertProjectStatusUpdateMaterialFabricationAndDeliveries?: UpsertProjectStatusUpdateMaterialFabricationAndDeliveriesDto;
  createOrderAcknowledgement?: OrderAcknowledgementCreateDto;
  updateOrderAcknowledgement?: OrderAcknowledgementUpdateWithIdDto;
  upsertOrderAcknowledgementDrawingSubmittals?: UpsertOrderAcknowledgementDrawingSubmittalsDto;
  upsertOrderAcknowledgementMaterialAquisitionLeadTimes?: UpsertOrderAcknowledgementMaterialAquisitionLeadTimesDto;
  upsertOrderAcknowledgementMaterialFabricationAndDeliveries?: UpsertOrderAcknowledgementMaterialFabricationAndDeliveriesDto;
  upsertProjectDocumentFiles?: UpsertProjectDocumentFilesDto;
  createTransmittal?: TransmittalCreateDto;
  updateTransmittal?: TransmittalUpdateWithIdDto;
  updateSubmittals?: UpdateSubmittalsDto;
  createSubmittal?: SubmittalCreateDto;
  updateSubmittal?: SubmittalUpdateWithIdDto;
  upsertSubmittals?: UpsertSubmittalsDto;
  createRFI?: RFICreateDto;
  updateRFI?: RFIUpdateWithIdDto;
  upsertEntityLinks?: Array<EntityLinkUpsertsDto> | null;
  createServiceTask?: ServiceTaskCreateDto;
  updateServiceTask?: ServiceTaskUpdateWithIdDto;
  serviceTaskProductionDirectiveUpsert?: ServiceTaskProductionDirectiveUpsertDto;
};
